/*
  # Add Expert Presentation Section to Reports

  1. Changes
    - Add `expert_presentation_section` column to `expertise_reports` table
    - This section will be the first section in the report, introducing the expert

  2. Important Notes
    - This section will be generated by AI based on the expert's profile
    - It appears before all other sections in the report
*/

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'expertise_reports' AND column_name = 'expert_presentation_section'
  ) THEN
    ALTER TABLE expertise_reports ADD COLUMN expert_presentation_section text DEFAULT '';
  END IF;
END $$;
